// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

package org.grapheco.pandadb.network;

public final class Query {
  private Query() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryRequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:org.grapheco.pandadb.network.QueryRequest)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string statement = 1;</code>
     */
    java.lang.String getStatement();
    /**
     * <code>optional string statement = 1;</code>
     */
    com.google.protobuf.ByteString
    getStatementBytes();

    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */
    int getParametersCount();
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */
    boolean containsParameters(
            java.lang.String key);
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getParameters();
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getParametersMap();
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */

    com.google.protobuf.ByteString getParametersOrDefault(
            java.lang.String key,
            com.google.protobuf.ByteString defaultValue);
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */

    com.google.protobuf.ByteString getParametersOrThrow(
            java.lang.String key);
  }
  /**
   * Protobuf type {@code org.grapheco.pandadb.network.QueryRequest}
   */
  public  static final class QueryRequest extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:org.grapheco.pandadb.network.QueryRequest)
          QueryRequestOrBuilder {
    // Use QueryRequest.newBuilder() to construct.
    private QueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryRequest() {
      statement_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              statement_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                parameters_ = com.google.protobuf.MapField.newMapField(
                        ParametersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                      parameters = input.readMessage(
                      ParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              parameters_.getMutableMap().put(parameters.getKey(), parameters.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
      switch (number) {
        case 2:
          return internalGetParameters();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.grapheco.pandadb.network.Query.QueryRequest.class, org.grapheco.pandadb.network.Query.QueryRequest.Builder.class);
    }

    private int bitField0_;
    public static final int STATEMENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object statement_;
    /**
     * <code>optional string statement = 1;</code>
     */
    public java.lang.String getStatement() {
      java.lang.Object ref = statement_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statement_ = s;
        return s;
      }
    }
    /**
     * <code>optional string statement = 1;</code>
     */
    public com.google.protobuf.ByteString
    getStatementBytes() {
      java.lang.Object ref = statement_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        statement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 2;
    private static final class ParametersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
              java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
                      .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                              org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryRequest_ParametersEntry_descriptor,
                              com.google.protobuf.WireFormat.FieldType.STRING,
                              "",
                              com.google.protobuf.WireFormat.FieldType.BYTES,
                              com.google.protobuf.ByteString.EMPTY);
    }
    private com.google.protobuf.MapField<
            java.lang.String, com.google.protobuf.ByteString> parameters_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetParameters() {
      if (parameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
                ParametersDefaultEntryHolder.defaultEntry);
      }
      return parameters_;
    }

    public int getParametersCount() {
      return internalGetParameters().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */

    public boolean containsParameters(
            java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetParameters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getParameters() {
      return getParametersMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getParametersMap() {
      return internalGetParameters().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */

    public com.google.protobuf.ByteString getParametersOrDefault(
            java.lang.String key,
            com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
              internalGetParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; parameters = 2;</code>
     */

    public com.google.protobuf.ByteString getParametersOrThrow(
            java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
              internalGetParameters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getStatementBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statement_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
              : internalGetParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                parameters = ParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
                .setKey(entry.getKey())
                .setValue(entry.getValue())
                .build();
        output.writeMessage(2, parameters);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatementBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statement_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
              : internalGetParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                parameters = ParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
                .setKey(entry.getKey())
                .setValue(entry.getValue())
                .build();
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(2, parameters);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.grapheco.pandadb.network.Query.QueryRequest)) {
        return super.equals(obj);
      }
      org.grapheco.pandadb.network.Query.QueryRequest other = (org.grapheco.pandadb.network.Query.QueryRequest) obj;

      boolean result = true;
      result = result && getStatement()
              .equals(other.getStatement());
      result = result && internalGetParameters().equals(
              other.internalGetParameters());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STATEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getStatement().hashCode();
      if (!internalGetParameters().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParameters().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.grapheco.pandadb.network.Query.QueryRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.grapheco.pandadb.network.Query.QueryRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.grapheco.pandadb.network.QueryRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:org.grapheco.pandadb.network.QueryRequest)
            org.grapheco.pandadb.network.Query.QueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
              int number) {
        switch (number) {
          case 2:
            return internalGetParameters();
          default:
            throw new RuntimeException(
                    "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
              int number) {
        switch (number) {
          case 2:
            return internalGetMutableParameters();
          default:
            throw new RuntimeException(
                    "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.grapheco.pandadb.network.Query.QueryRequest.class, org.grapheco.pandadb.network.Query.QueryRequest.Builder.class);
      }

      // Construct using org.grapheco.pandadb.network.Query.QueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        statement_ = "";

        internalGetMutableParameters().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor;
      }

      public org.grapheco.pandadb.network.Query.QueryRequest getDefaultInstanceForType() {
        return org.grapheco.pandadb.network.Query.QueryRequest.getDefaultInstance();
      }

      public org.grapheco.pandadb.network.Query.QueryRequest build() {
        org.grapheco.pandadb.network.Query.QueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.grapheco.pandadb.network.Query.QueryRequest buildPartial() {
        org.grapheco.pandadb.network.Query.QueryRequest result = new org.grapheco.pandadb.network.Query.QueryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.statement_ = statement_;
        result.parameters_ = internalGetParameters();
        result.parameters_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.grapheco.pandadb.network.Query.QueryRequest) {
          return mergeFrom((org.grapheco.pandadb.network.Query.QueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.grapheco.pandadb.network.Query.QueryRequest other) {
        if (other == org.grapheco.pandadb.network.Query.QueryRequest.getDefaultInstance()) return this;
        if (!other.getStatement().isEmpty()) {
          statement_ = other.statement_;
          onChanged();
        }
        internalGetMutableParameters().mergeFrom(
                other.internalGetParameters());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        org.grapheco.pandadb.network.Query.QueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.grapheco.pandadb.network.Query.QueryRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object statement_ = "";
      /**
       * <code>optional string statement = 1;</code>
       */
      public java.lang.String getStatement() {
        java.lang.Object ref = statement_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statement_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string statement = 1;</code>
       */
      public com.google.protobuf.ByteString
      getStatementBytes() {
        java.lang.Object ref = statement_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          statement_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string statement = 1;</code>
       */
      public Builder setStatement(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        statement_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string statement = 1;</code>
       */
      public Builder clearStatement() {

        statement_ = getDefaultInstance().getStatement();
        onChanged();
        return this;
      }
      /**
       * <code>optional string statement = 1;</code>
       */
      public Builder setStatementBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        statement_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
              java.lang.String, com.google.protobuf.ByteString> parameters_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetParameters() {
        if (parameters_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
                  ParametersDefaultEntryHolder.defaultEntry);
        }
        return parameters_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetMutableParameters() {
        onChanged();;
        if (parameters_ == null) {
          parameters_ = com.google.protobuf.MapField.newMapField(
                  ParametersDefaultEntryHolder.defaultEntry);
        }
        if (!parameters_.isMutable()) {
          parameters_ = parameters_.copy();
        }
        return parameters_;
      }

      public int getParametersCount() {
        return internalGetParameters().getMap().size();
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */

      public boolean containsParameters(
              java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetParameters().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParametersMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getParameters() {
        return getParametersMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getParametersMap() {
        return internalGetParameters().getMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */

      public com.google.protobuf.ByteString getParametersOrDefault(
              java.lang.String key,
              com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                internalGetParameters().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */

      public com.google.protobuf.ByteString getParametersOrThrow(
              java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                internalGetParameters().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParameters() {
        getMutableParameters().clear();
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */

      public Builder removeParameters(
              java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableParameters().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
      getMutableParameters() {
        return internalGetMutableParameters().getMutableMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */
      public Builder putParameters(
              java.lang.String key,
              com.google.protobuf.ByteString value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableParameters().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; parameters = 2;</code>
       */

      public Builder putAllParameters(
              java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        getMutableParameters().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.grapheco.pandadb.network.QueryRequest)
    }

    // @@protoc_insertion_point(class_scope:org.grapheco.pandadb.network.QueryRequest)
    private static final org.grapheco.pandadb.network.Query.QueryRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.grapheco.pandadb.network.Query.QueryRequest();
    }

    public static org.grapheco.pandadb.network.Query.QueryRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryRequest>
            PARSER = new com.google.protobuf.AbstractParser<QueryRequest>() {
      public QueryRequest parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryRequest> getParserForType() {
      return PARSER;
    }

    public org.grapheco.pandadb.network.Query.QueryRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:org.grapheco.pandadb.network.QueryResponse)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes resultInBytes = 1;</code>
     */
    com.google.protobuf.ByteString getResultInBytes();
  }
  /**
   * Protobuf type {@code org.grapheco.pandadb.network.QueryResponse}
   */
  public  static final class QueryResponse extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:org.grapheco.pandadb.network.QueryResponse)
          QueryResponseOrBuilder {
    // Use QueryResponse.newBuilder() to construct.
    private QueryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryResponse() {
      resultInBytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              resultInBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.grapheco.pandadb.network.Query.QueryResponse.class, org.grapheco.pandadb.network.Query.QueryResponse.Builder.class);
    }

    public static final int RESULTINBYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString resultInBytes_;
    /**
     * <code>optional bytes resultInBytes = 1;</code>
     */
    public com.google.protobuf.ByteString getResultInBytes() {
      return resultInBytes_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!resultInBytes_.isEmpty()) {
        output.writeBytes(1, resultInBytes_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!resultInBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, resultInBytes_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.grapheco.pandadb.network.Query.QueryResponse)) {
        return super.equals(obj);
      }
      org.grapheco.pandadb.network.Query.QueryResponse other = (org.grapheco.pandadb.network.Query.QueryResponse) obj;

      boolean result = true;
      result = result && getResultInBytes()
              .equals(other.getResultInBytes());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESULTINBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getResultInBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.grapheco.pandadb.network.Query.QueryResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.grapheco.pandadb.network.Query.QueryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.grapheco.pandadb.network.QueryResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:org.grapheco.pandadb.network.QueryResponse)
            org.grapheco.pandadb.network.Query.QueryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.grapheco.pandadb.network.Query.QueryResponse.class, org.grapheco.pandadb.network.Query.QueryResponse.Builder.class);
      }

      // Construct using org.grapheco.pandadb.network.Query.QueryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resultInBytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.grapheco.pandadb.network.Query.internal_static_org_grapheco_pandadb_network_QueryResponse_descriptor;
      }

      public org.grapheco.pandadb.network.Query.QueryResponse getDefaultInstanceForType() {
        return org.grapheco.pandadb.network.Query.QueryResponse.getDefaultInstance();
      }

      public org.grapheco.pandadb.network.Query.QueryResponse build() {
        org.grapheco.pandadb.network.Query.QueryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.grapheco.pandadb.network.Query.QueryResponse buildPartial() {
        org.grapheco.pandadb.network.Query.QueryResponse result = new org.grapheco.pandadb.network.Query.QueryResponse(this);
        result.resultInBytes_ = resultInBytes_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.grapheco.pandadb.network.Query.QueryResponse) {
          return mergeFrom((org.grapheco.pandadb.network.Query.QueryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.grapheco.pandadb.network.Query.QueryResponse other) {
        if (other == org.grapheco.pandadb.network.Query.QueryResponse.getDefaultInstance()) return this;
        if (other.getResultInBytes() != com.google.protobuf.ByteString.EMPTY) {
          setResultInBytes(other.getResultInBytes());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        org.grapheco.pandadb.network.Query.QueryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.grapheco.pandadb.network.Query.QueryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString resultInBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes resultInBytes = 1;</code>
       */
      public com.google.protobuf.ByteString getResultInBytes() {
        return resultInBytes_;
      }
      /**
       * <code>optional bytes resultInBytes = 1;</code>
       */
      public Builder setResultInBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        resultInBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes resultInBytes = 1;</code>
       */
      public Builder clearResultInBytes() {

        resultInBytes_ = getDefaultInstance().getResultInBytes();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.grapheco.pandadb.network.QueryResponse)
    }

    // @@protoc_insertion_point(class_scope:org.grapheco.pandadb.network.QueryResponse)
    private static final org.grapheco.pandadb.network.Query.QueryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.grapheco.pandadb.network.Query.QueryResponse();
    }

    public static org.grapheco.pandadb.network.Query.QueryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryResponse>
            PARSER = new com.google.protobuf.AbstractParser<QueryResponse>() {
      public QueryResponse parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryResponse> getParserForType() {
      return PARSER;
    }

    public org.grapheco.pandadb.network.Query.QueryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_org_grapheco_pandadb_network_QueryRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_org_grapheco_pandadb_network_QueryRequest_ParametersEntry_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_org_grapheco_pandadb_network_QueryRequest_ParametersEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_org_grapheco_pandadb_network_QueryResponse_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_org_grapheco_pandadb_network_QueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\013query.proto\022\034org.grapheco.pandadb.netw" +
                    "ork\"\244\001\n\014QueryRequest\022\021\n\tstatement\030\001 \001(\t\022" +
                    "N\n\nparameters\030\002 \003(\0132:.org.grapheco.panda" +
                    "db.network.QueryRequest.ParametersEntry\032" +
                    "1\n\017ParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
                    "\030\002 \001(\014:\0028\001\"&\n\rQueryResponse\022\025\n\rresultInB" +
                    "ytes\030\001 \001(\0142y\n\021PandaQueryService\022d\n\005Query" +
                    "\022*.org.grapheco.pandadb.network.QueryReq" +
                    "uest\032+.org.grapheco.pandadb.network.Quer" +
                    "yResponse\"\0000\001B\036\n\034org.grapheco.pandadb.ne",
            "tworkb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_org_grapheco_pandadb_network_QueryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor,
            new java.lang.String[] { "Statement", "Parameters", });
    internal_static_org_grapheco_pandadb_network_QueryRequest_ParametersEntry_descriptor =
            internal_static_org_grapheco_pandadb_network_QueryRequest_descriptor.getNestedTypes().get(0);
    internal_static_org_grapheco_pandadb_network_QueryRequest_ParametersEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_org_grapheco_pandadb_network_QueryRequest_ParametersEntry_descriptor,
            new java.lang.String[] { "Key", "Value", });
    internal_static_org_grapheco_pandadb_network_QueryResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_org_grapheco_pandadb_network_QueryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_org_grapheco_pandadb_network_QueryResponse_descriptor,
            new java.lang.String[] { "ResultInBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
